name: Lint
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  star:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - run: pnpm install
      - name: Lint code
        run: pnpm lint:ci