name: Spellcheck
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@adb9472decdd5da99eeca3c56d731fb7dce12cf8 # v2.7.0
